export { default as DashboardHeader } from './DashboardHeader'
export { default as ExamTimeline } from './ExamTimeline'
export { default as KPISection } from './KPISection'
export { default as TodaysExamCard } from './TodaysExamCard'
export { default as RoomAllotmentTable } from './RoomAllotmentTable'
export { default as OccupancyChart } from './OccupancyChart'
export { default as UpcomingExams } from './UpcomingExams'
export { default as RecentActivity } from './RecentActivity'
export { default as ExamOverview } from './ExamOverview'

export type { DashboardHeaderProps } from './DashboardHeader'
export type { ExamTimelineProps, ExamTimelineItem } from './ExamTimeline'
export type { KPISectionProps, KPICard } from './KPISection'
export type { TodaysExamCardProps, TodaysExamData } from './TodaysExamCard'
export type { RoomAllotmentTableProps, RoomAllotmentRow } from './RoomAllotmentTable'
export type { OccupancyChartProps } from './OccupancyChart'
export type { UpcomingExamsProps, UpcomingExamItem } from './UpcomingExams'
export type { RecentActivityProps, RecentActivityItem } from './RecentActivity'
export type { ExamOverviewProps } from './ExamOverview'
